"""
Interfaces for forecasting service.
"""
from typing import Protocol, Any
from uuid import UUID


class PredictionRepositoryProtocol(Protocol):
    """Interface for prediction repository."""

    async def create(self, prediction: Any) -> Any: ...
    async def get_by_id(self, prediction_id: UUID) -> Any: ...
    async def get_by_user(
        self, user_id: UUID, limit: int = 20, offset: int = 0
    ) -> list[Any]: ...


class UnitOfWorkProtocol(Protocol):
    """Unit of Work pattern."""

    predictions: PredictionRepositoryProtocol

    async def __aenter__(self) -> "UnitOfWorkProtocol": ...
    async def __aexit__(self, exc_type, exc_val, exc_tb) -> None: ...
    async def commit(self) -> None: ...
    async def rollback(self) -> None: ...


class PredictorProtocol(Protocol):
    """Interface for ML predictor."""

    def predict(self, features: dict[str, Any]) -> Any: ...
    def get_model_info(self) -> dict[str, Any]: ...
    def is_loaded(self) -> bool: ...


class ModelRegistryProtocol(Protocol):
    """Interface for model registry."""

    def get_active_model(self) -> str: ...
    def get_all_models(self) -> list[str]: ...
    def activate_model(self, model_version: str) -> None: ...